// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMPyUPc7oWfwWC14zwBuQ33lroIMP0fE',
    appId: '1:709007696441:android:09fef7637dfb5893cc63e8',
    messagingSenderId: '709007696441',
    projectId: 'facturainvent',
    storageBucket: 'facturainvent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmoZlEBPJXoC5hqRQDaJj77e3C_-VujCU',
    appId: '1:709007696441:ios:110da1b73f6662f4cc63e8',
    messagingSenderId: '709007696441',
    projectId: 'facturainvent',
    storageBucket: 'facturainvent.firebasestorage.app',
    iosBundleId: 'com.miguel.facturainvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmoZlEBPJXoC5hqRQDaJj77e3C_-VujCU',
    appId: '1:709007696441:ios:110da1b73f6662f4cc63e8',
    messagingSenderId: '709007696441',
    projectId: 'facturainvent',
    storageBucket: 'facturainvent.firebasestorage.app',
    iosBundleId: 'com.miguel.facturainvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsKqAK_4kk5uNPX0rJW50j2AN-cMFtxVY',
    appId: '1:709007696441:web:00816ad24e68719fcc63e8',
    messagingSenderId: '709007696441',
    projectId: 'facturainvent',
    authDomain: 'facturainvent.firebaseapp.com',
    storageBucket: 'facturainvent.firebasestorage.app',
    measurementId: 'G-4P0P228NGR',
  );
}
